DROP TABLE IF EXISTS Links;
DROP TABLE IF EXISTS Clicks;
DROP TABLE IF EXISTS Users;

CREATE TABLE Users (
  id TEXT NOT NULL PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  password INTEGER NOT NULL,
  createdAt INTEGER NOT NULL
);

CREATE TABLE Links (
  slug TEXT NOT NULL PRIMARY KEY,
  redirectTo TEXT NOT NULL,
  userId TEXT NOT NULL,
  createdAt INTEGER NOT NULL,
  FOREIGN KEY (userId) REFERENCES Users(id)
);

CREATE TABLE Clicks (
  slug TEXT NOT NULL,
  date INTEGER NOT NULL,
  FOREIGN KEY (slug) REFERENCES Links(slug)
);
